"""hello

Revision ID: 6734ef2a3cbc
Revises: b1df024fa06b
Create Date: 2026-05-07 09:58:02.913537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6734ef2a3cbc'
down_revision = 'b1df024fa06b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastname', sa.String(length=100), nullable=False, server_default='Unknown'))
        batch_op.add_column(sa.Column('firstname', sa.String(length=100), nullable=False, server_default='Unknown'))
        batch_op.add_column(sa.Column('middlename', sa.String(length=100), nullable=False, server_default='Unknown'))
        batch_op.drop_column('middle_name')
        batch_op.drop_column('employee_id')
        batch_op.drop_column('first_name')
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('employee_id', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('middle_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('middlename')
        batch_op.drop_column('firstname')
        batch_op.drop_column('lastname')

    # ### end Alembic commands ###
